clip_image:
  working_directory: D:/GitHubProjects/STDL_vegroof_production
  inputs:
    ortho_directory: sources/rasters/ZH
    aoi: sources/Footprint/ZH/00-AVBodenbedGeb_updated.gpkg
    epsg: 'epsg:2056'
  outputs: 
    result_directory: ML/results
    clip_ortho_directory: ML/results/infer_moitie/tiles
    extent_ortho_directory: ML/results/infer_moitie/extent
