hydra:
  run:
    dir: 02_intermediate/th/${now:%Y-%m-%d}/${now:%H-%M-%S}

dev:
  working_directory: C:/Users/cmarmy/Documents/STDL/proj-vegroofs/data_test
  ortho_directory: 02_intermediate/images/scratch/tiles
  tile_delimitation: 02_intermediate/images/scratch/extent/
  ndvi_directory: 02_intermediate/images/scratch/ndvi
  lum_directory: 02_intermediate/images/scratch/lum
  roofs_file: 01_initial/gt/gt_test.gpkg
  roofs_layer: 
  gt: True
  green_tag: 'veg_new'
  green_cls: 'class'
  chm_layer: 02_intermediate/autres/CHM_AOI.gpkg
  results_directory: 03_results/scratch_ratio/
  egid_train_test: egid_train_test_gt.csv
  predicate_sjoin: 'within'
  th_ndvi: -1 # no thresholding -1
  th_lum: 210000 # no thresholding 765 or 210000
  cls_ml: 'binary' # 'binary' 'multi' 'multi_aggreg'
  model_ml: 'LR' # 'LR' 'RF'
  trained_model_dir: 03_results/scratch_ratio/
  epsg: 'epsg:2056'


# prod: 
#   working_directory: C:/Users/cmarmy/Documents/STDL/proj-vegroofs/data
#   ortho_directory: 02_intermediate/images/scratch/tiles
#   tile_delimitation: 02_intermediate/images/scratch/extent/
#   ndvi_directory: 02_intermediate/images/scratch/ndvi
#   lum_directory: 02_intermediate/images/scratch/lum
#   roofs_gt: 02_intermediate/gt/gt_tot.gpkg # 02_intermediate/autres/swissbuilding_aoi.gpkg
#   roofs_layer: joined_layer
#   green_tag: 'veg_new'
#   green_cls: 'class'
#   chm_layer: 02_intermediate/autres/CHM_AOI.gpkg
#   results_directory: 03_results/scratch_sb_noratio/
#   egid_train_test: egid_train_test_gt.csv
#   roofs_lr: 02_intermediate/autres/swissbuilding_aoi.gpkg # 02_intermediate/gt/gt_tot.gpkg #02_intermediate/th/2024-06-14/15-02-41/0_765_gt_tot_green.shp
#   predicate_sjoin: 'within'
#   th_ndvi: -1 # no thresholding -1
#   th_lum: 210000 # no thresholding 765 or 210000
#   cls_lr: 'multi' # 'binary' 'multi' 'multi_aggreg'
#   model_ml: 'LR' # 'LR' 'RF'
#   epsg: 'epsg:2056'

