hydra:
  run:
    dir: ./data_test/th/${now:%Y-%m-%d}/${now:%H-%M-%S}

logReg_approach_A2Z:
  logistic_regression.py:
  working_directory: C:/Users/cmarmy/Documents/STDL/proj-vegroofs/data_test
  ortho_directory: 02_intermediate/images/scratch/2022/ZH/tiles
  aoi: C:/Users/cmarmy/Documents/STDL/proj-vegroofs/data/01_initial/aoi/STDL_ZH_AOI.shp
  tile_delimitation: 02_intermediate/aoi/clip/szh/AOI.shp
  ndvi_directory: 02_intermediate/images/scratch/2022/ZH/ndvi
  lum_directory: 02_intermediate/images/scratch/2022/ZH/lum
  roofs_file: 02_intermediate/gt_test.shp
  roofs_layer: gt_zh
  th_ndvi: -0.08
  th_lum: 600
  lr_directory: 02_intermediate/images/scratch/2022/ZH
