hydra:
  run:
    dir: 02_intermediate/th/${now:%Y-%m-%d}/${now:%H-%M-%S}

lr_workflow:
  working_directory: C:/Users/cmarmy/Documents/STDL/proj-vegroofs/data_test
  ortho_directory: 02_intermediate/images/scratch/2022/ZH/tiles
  ndvi_directory: 02_intermediate/images/scratch/2022/ZH/ndvi
  lum_directory: 02_intermediate/images/scratch/2022/ZH/lum
  lr_directory: 02_intermediate/lr
  aoi: C:/Users/cmarmy/Documents/STDL/proj-vegroofs/data/01_initial/aoi/STDL_ZH_AOI.shp
  tile_delimitation: 02_intermediate/images/scratch/2022/ZH/extent/
  roofs_gt: 02_intermediate/gt_test.shp 
  roofs_layer: gt_zh
  th_ndvi: 0 # no thresholding -1
  th_lum: 400 # no thresholding 765
  epsg: 'epsg:2056'

prod: 
  working_directory: C:/Users/cmarmy/Documents/STDL/proj-vegroofs/data
  ortho_directory: 02_intermediate/images/scratch/2023/GE/tiles
  ndvi_directory: 02_intermediate/images/scratch/2023/GE/ndvi
  lum_directory: 02_intermediate/images/scratch/2023/GE/lum
  lr_directory: 02_intermediate/lr
  aoi: C:/Users/cmarmy/Documents/STDL/proj-vegroofs/data/01_initial/aoi/STDL_ZH_AOI.shp
  tile_delimitation: 02_intermediate/images/scratch/2023/GE/extent/
  roofs_gt: 01_initial/gt/GE/label/gt_ge_bgu.shp
  roofs_layer: gt_zh
  roofs_lr: 02_intermediate/th/2024-03-06/12-25-37/-1_765_hydraroof_lr.shp
  th_ndvi: -1 # no thresholding -1
  th_lum: 765 # no thresholding 765
  epsg: 'epsg:2056'