hydra:
  run:
    dir: 02_intermediate/th/${now:%Y-%m-%d}/${now:%H-%M-%S}

dev:
  working_directory: D:/GitHubProjects/STDL_vegroof_production
  ortho_directory: ML/results/infer_moitie/tiles
  tile_delimitation: ML/results/infer_moitie/tiles/extent
  ndvi_directory: ML/results/infer_moitie/ndvi
  lum_directory: ML/results/infer_moitie/lum
  roofs_file: sources/Footprint/ZH/00-AVBodenbedGeb_updated.gpkg
  roofs_layer: 
  gt: False
  green_tag: 'veg_new_3'
  green_cls: 'class_3'
  chm_layer: sources/CHM/ZH/chm_ZH_total.shp
  results_directory: ML/results
  egid_train_test: egid_train_test_gt.csv
  th_ndvi: 0 # no thresholding -1
  th_lum: 500 # no thresholding 765 or 210000
  cls_ml: 'binary' # 'binary' 'multi' 'multi_aggreg'
  model_ml: 'LR' # 'LR' 'RF'
  trained_model_dir: ML/models
  epsg: 'epsg:2056'
  do_overlay: False
